### ISSUE TITLE
Clarification on Cloudinary example

### ISSUE THREAD

**Issue by pcooney10** [graphcool-examples/functions#21]
Does the Cloudinary example store the image twice - once in the graphcool File type, and then a second time on the Cloudinary server? Thanks !

**Comment by marktani** [comment]
That's something I'd have to ask @heymartinadams as well 🤗

**Comment by heymartinadams** [comment]
@pcooney10, I believe so. Might be good to create a delete `mutation` as part of your app, so you don’t have it in two locations.

Ended up using Graphcool’s `File` system instead of Cloudinary, and am performing cropping function locally instead: https://github.com/heymartinadams/react-graphql/blob/1fe90a9a8b7623f8c8b5cfb440aa556d65f28241/files-with-apollo/src/components/CreatePage.js

**Comment by pcooney10** [comment]
Ok great, thank you for clarifying
