### ISSUE TITLE
Firebase Auth with Google Cloud Functions

### ISSUE THREAD

**Issue by marktani** [graphcool-examples/functions#31]
Thanks to @jhalborg for contributing this example: https://gist.github.com/jhalborg/5042201f558034243376cffb55111d85

Would love to see a step-by-step guide for this, so if anyone wants to get their hands dirty, feel free  to create a PR 😄 I'd be happy to review it

**Comment by jhalborg** [comment]
Might write it up later, but essentially what's happening is:

1. Login/sign up the user on the client against Firebase using the Auth SDK to receive a Firebase token
2. Send the auth/ID token as a param to your schema with the new query, getCustomToken
3. In your cloud function, use the Firebase Admin SDK to validate the given Firebase ID token. 
4. If it is valid, look for the firebase userID (can be extracted from the verified/decoded token) in your Graphcool users. 
4a. If one is found, get the Graphcool user ID
4b. If the user does not yet exist on Graphcool, create one and get the ID of the new user
5. Generate a Graphcool access token from the users ID using the graphcool lib.
6. Embed the generated Graphcool token as a 'claim' in a newly minted Firebase auth custom token and return it
7. On the client, re-sign in the user using the `signInWithCustomToken(token)` 

You can now access Firebase with the created token, and Graphcool with the firebasetoken.claims.graphcool token - happy day! :-) If you don't like having the tokens embedded, you can skip 6/7 and just return the Graphcool token and keep the two separate on the client if that's what you prefer. 

The Firebase docs and jwt.io is your friend when building this stuff ;-)

**Comment by FredyC** [comment]
@jhalborg Thank you very much for example and explanation. I just want to clarify point number 3. By cloud function, you mean a function deployed to eg. AWS or is that something that can be done with GraphCool Functions?

I am not sure how those Schema Extension functions can be created. There are only Server-Side subscription and Request Pipeline. Either one of them doesn't feel like the right thing since it requires some trigger. From your snippet of `schema-extension.sdl`  I get the impression that this custom mutation should be actual trigger.

**Comment by mkozhukharenko** [comment]
here is one https://github.com/Gregor1971/firebase-graphcool-authentication

**Comment by FredyC** [comment]
@mkozhukharenko Looks good, but I used Firebase Functions instead of serverless. There is great advantage that you don't need to worry about service key. Just receive token, verify it and return it's payload. In Graphcool I can then just take care of finding/creating user without any Firebase interference.
```js
const functions = require('firebase-functions')
const admin = require('firebase-admin')

admin.initializeApp(functions.config().firebase)

exports.verifyToken = functions.https.onRequest((req, res) => {
  const { idToken } = req.query
  if (!idToken) {
    res.json({ error: 'Missing idToken in query' })
    return
  }
  admin.auth().verifyIdToken(idToken)
    .then(authUser => res.json(authUser))
    .catch(() => res.json({ error: 'Could not verify id token with Firebase' }))
})
```

**Comment by marktani** [comment]
Thanks so much @Gregor1971, I just merged your PR: https://github.com/graphcool-examples/functions/pull/66. 🎉
